# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kf_cpp <- function(A, B, C, D, Q, R, mu0, P0, u_mat, y_mat) {
    .Call(`_kfsang_kf_cpp`, A, B, C, D, Q, R, mu0, P0, u_mat, y_mat)
}

nstep_cpp <- function(A, B, C, D, x0, u_mat) {
    .Call(`_kfsang_nstep_cpp`, A, B, C, D, x0, u_mat)
}

onestep_cpp <- function(A, B, C, D, x, u) {
    .Call(`_kfsang_onestep_cpp`, A, B, C, D, x, u)
}

rcpparma_hello_world <- function() {
    .Call(`_kfsang_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_kfsang_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_kfsang_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_kfsang_rcpparma_bothproducts`, x)
}

update_system_cpp <- function(par, dims, dt) {
    .Call(`_kfsang_update_system_cpp`, par, dims, dt)
}

update_system_lw_cpp <- function(x0, par, dims, dt) {
    .Call(`_kfsang_update_system_lw_cpp`, x0, par, dims, dt)
}

update_system_lw_onestep_cpp <- function(par, dims, dt, x, u) {
    .Call(`_kfsang_update_system_lw_onestep_cpp`, par, dims, dt, x, u)
}

